DEFAULT_STRING_LENGTH = 256
DEFAULT_FLOAT_PRECISION = 1e-7
DEFAULT_REDSHIFT_RELATIVE_PRECISION = 1e-7

DEFAULT_ABS_TOLERANCE = 1e-10
DEFAULT_REL_TOLERANCE = 1e-8

DEFAULT_QUADRATURE_RTOL = 1e-8
DEFAULT_QUADRATURE_ATOL = 1e-25

# value of dtheta/dz where we will switch to a Levin integration strategy
DEFAULT_LEVIN_THRESHOLD = 1.0

DEFAULT_GKSOURCE_NUMERIC_POLICY = "maximize-WKB"
DEFAULT_QUADSOURCE_NUMERIC_POLICY = "maximize-WKB"
