"""What limits the code-against-eq.-(22) comparison of KOHRI-TERADA-ORACLE.md section 7.1.

Runs from the repository root with no arguments, no Ray and no datastore:

    PYTHONPATH=. ./venv/bin/python docs/radiation-oracle/eq22_rounding.py

Its stdout is section 7.2 of `KOHRI-TERADA-ORACLE.md`. It does not modify or
supersede `kt_verification.py`, which produced sections 4 to 7.1; it imports it,
so that the double-precision eq. (22) and head scored here are exactly the ones
section 7.1 used.

Section 1 and the preamble of section 7.1 attribute the 3.18e-10 worst deviation
of N from -9/8 against eq. (22) to the head 0 -> x_min being quadratured and
subtracted. This script separates the two candidate causes on all nine b = 0
cases, by evaluating each in 50-digit mpmath:

  * eq. (22) itself, transcribed here independently of both
    `kt_verification.I_RD` and `ComputeTargets/tests/kohri_terada.py` with the
    Ci/Si pairing of section 2 item 1 (the (v - u) pair carries +Ci and -Si);
  * the head, integrating eq. (15)'s integrand with eq. (16) at w = 1/3 and
    eq. (19) written out in mpmath.

and then recomputing N with each replaced by its 50-digit value.
"""

import math
import os
import sys

import mpmath as mp
from scipy.integrate import quad

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import kt_verification as KT  # noqa: E402
from ComputeTargets.tests.test_quadsource_integral import (  # noqa: E402
    Case,
    SHAPES,
    X_RESP_VALUES,
)

mp.mp.dps = 50
S3 = mp.sqrt(3)
KT_NORM = -9.0 / 8.0


def I_RD_mp(v, u, x):
    """KT eq. (22), literal form, in mpmath; Ci of |.| throughout. No case is on the resonance."""
    v, u, x = mp.mpf(v), mp.mpf(u), mp.mpf(x)
    d = u * u + v * v - 3
    cu, su = mp.cos(u * x / S3), mp.sin(u * x / S3)
    cv, sv = mp.cos(v * x / S3), mp.sin(v * x / S3)
    rational = (
        u * v * d * x**3 * mp.sin(x)
        - 6 * u * v * x**2 * cu * cv
        + 6 * S3 * u * x * cu * sv
        + 6 * S3 * v * x * su * cv
        - 3 * (6 + d * x**2) * su * sv
    )
    sin_bracket = (
        mp.ci(abs(1 - (v - u) / S3) * x)
        + mp.ci(abs(1 + (v - u) / S3) * x)
        - mp.ci(abs(1 - (v + u) / S3) * x)
        - mp.ci((1 + (v + u) / S3) * x)
        + mp.log(abs((3 - (u + v) ** 2) / (3 - (u - v) ** 2)))
    )
    cos_bracket = (
        -mp.si((1 - (v - u) / S3) * x)
        - mp.si((1 + (v - u) / S3) * x)
        + mp.si((1 - (v + u) / S3) * x)
        + mp.si((1 + (v + u) / S3) * x)
    )
    return (
        3
        / (4 * u**3 * v**3 * x)
        * (
            -4 / x**3 * rational
            + d * d * (mp.sin(x) * sin_bracket + mp.cos(x) * cos_bracket)
        )
    )


def Phi_mp(y):
    """KT eq. (19). 50 digits absorb the closed form's cancellation at every y used here."""
    z = y / S3
    return 9 / (y * y) * (mp.sin(z) / z - mp.cos(z))


def dPhi_mp(y):
    z = y / S3
    s, c = mp.sin(z), mp.cos(z)
    g = s / z - c
    gp = (c / z - s / (z * z) + s) / S3
    return 9 * gp / (y * y) - 18 * g / (y * y * y)


def f_RD_mp(v, u, xb):
    """KT eq. (16) at w = 1/3: c1 = 4/3, c2 = c3 = 4/9."""
    Pv, Pu = Phi_mp(v * xb), Phi_mp(u * xb)
    a, b = xb * v * dPhi_mp(v * xb), xb * u * dPhi_mp(u * xb)
    return mp.mpf(4) / 3 * Pv * Pu + mp.mpf(4) / 9 * (a * Pu + b * Pv + a * b)


def head_mp(v, u, x, x_min):
    v, u, x = mp.mpf(v), mp.mpf(u), mp.mpf(x)
    return mp.quad(lambda xb: (xb / x) * mp.sin(x - xb) * f_RD_mp(v, u, xb), [0, x_min])


def head_double(v, u, x, x_min):
    """Exactly section 7.1's head: kt_verification.check_5_against_the_code's quad call."""
    return quad(
        lambda xb: (xb / x) * math.sin(x - xb) * KT.f_general_w(v, u, xb),
        0.0,
        x_min,
        limit=200,
        epsabs=1e-18,
        epsrel=1e-13,
    )


def main():
    print("<!-- generated by docs/radiation-oracle/eq22_rounding.py -->")
    print()
    print(
        "| shape | x_resp | u | x | eq. (22) error | head / I | head's quad error | "
        "head error | N - (-9/8), as §7.1 | N - (-9/8), exact eq. (22) |"
    )
    print("|---|---|---|---|---|---|---|---|---|---|")

    worst_71, worst_exact, worst_head = 0.0, 0.0, 0.0
    for shape in SHAPES:
        for x_resp in X_RESP_VALUES:
            case = Case(b=0.0, shape=shape, x_resp=x_resp, exact=True)
            total = float(case.run(atol=1e-45, rtol=1e-12)["total"])
            k = shape.k
            u, v = shape.q / k, shape.r / k
            tau = case.model.functions.tau
            x = k * tau(case.z_resp)
            x_min = k * tau(case.z_source_max)

            I_exact = I_RD_mp(v, u, x)
            I_double = KT.I_RD(v, u, x)
            head, head_err = head_double(v, u, x, x_min)
            head_exact = head_mp(v, u, x, x_min)

            I_scale = abs(float(I_exact))
            eq22_err = float(abs(mp.mpf(I_double) - I_exact) / abs(I_exact))
            head_true_err = float(abs(mp.mpf(head) - head_exact)) / I_scale

            N_71 = total / ((I_double - head) / (k * k))
            N_exact = total / ((float(I_exact - head_exact)) / (k * k))
            dev_71, dev_exact = N_71 - KT_NORM, N_exact - KT_NORM
            worst_71 = max(worst_71, abs(dev_71))
            worst_exact = max(worst_exact, abs(dev_exact))
            worst_head = max(worst_head, head_true_err, head_err / I_scale)

            print(
                f"| {shape.name} | {x_resp:g} | {u:.4g} | {x:.4e} | {eq22_err:.2e} | "
                f"{abs(head) / I_scale:.2e} | {head_err / I_scale:.1e} | "
                f"{head_true_err:.1e} | {dev_71:+.2e} | {dev_exact:+.2e} |"
            )

    print()
    print(
        f"Worst |N + 9/8| with section 7.1's double-precision eq. (22) and head: "
        f"**{worst_71:.2e}**. With eq. (22) and the head both at 50 digits: "
        f"**{worst_exact:.2e}**. The head's error, declared or actual, never exceeds "
        f"**{worst_head:.1e}** of I."
    )


if __name__ == "__main__":
    main()
